version: '3.8'

services:
  mongo:
    image: mongo:7.0 
    ports:
      - "27017:27017" 
    volumes:
      - mongodb_data:/data/db 

  backend:
    build: ./backend 
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: mongodb://mongo:27017/tododb #
      NODE_ENV: docker
    depends_on:
      - mongo 

volumes:
  mongodb_data: