# name: CI/CD

# on:
#   push:
#     branches: [main]

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v3
#       - name: Set up Node.js
#         uses: actions/setup-node@v3
#         with:
#           node-version: 18

#       - name: Install dependencies
#         run: |
#           cd backend
#           npm install

#       - name: Run tests
#         run: |
#           cd backend
#           npx jest --detectOpenHandles

#       - name: Build Docker image
#         run: docker build -t todo-backend ./backend

name: CI/CD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install
        working-directory: ./backend

      # --- Pasos de Depuración ---
      - name: Debug - Verify current directory
        run: pwd
        working-directory: ./backend

      - name: Debug - List contents of node_modules/.bin
        run: ls -la node_modules/.bin/
        working-directory: ./backend

      - name: Debug - Verify Jest executable permissions
        run: ls -la node_modules/.bin/jest
        working-directory: ./backend 

      # --- Fin de Pasos de Depuración ---

      - name: Run tests
        run: npm test
        working-directory: ./backend

      - name: Build Docker image
        run: docker build -t todo-backend ./backend